from sqlalchemy.orm import Session
from app.database import SessionLocal, engine
from app import models
import random

def seed_data():
    db = SessionLocal()
    try:
        # Get some existing users
        users = db.query(models.User).limit(5).all()
        if not users:
            print("No users found. Please register some users first.")
            return

        # Get some existing skills
        skills = db.query(models.Skill).all()
        if not skills:
            print("No skills found. Please add some skills in the market first.")
            return

        examples = [
            {
                "title": "Quantum Tutor AI",
                "problem": "Students struggle with complex STEM concepts and lack consistent 24/7 personalized tutoring.",
                "vision": "Building the first neural-tutor that adapts to every student's learning pace.",
                "required_skills": ["Python Programming", "Data Analysis", "React Development"]
            },
            {
                "title": "Green campus Logistics",
                "problem": "Massive waste generated by courier services and document transfers within university walls.",
                "vision": "A zero-emission student-run delivery network for the digital age.",
                "required_skills": ["Digital Marketing", "React Development"]
            },
            {
                "title": "CodeFlow Beta",
                "problem": "Junior developers drowning in spaghetti code without real-time peer architectural reviews.",
                "vision": "The GitHub of the future - where architecture is reviewed before the first line is written.",
                "required_skills": ["Node.js", "Python Programming"]
            },
            {
                "title": "Hostel Harmony",
                "problem": "Unorganized student communities lead to resource waste and lack of collaborative energy.",
                "vision": "Digitizing the hostel experience, from automated laundry to shared resource tracking.",
                "required_skills": ["UI/UX Design", "React Development", "Node.js"]
            }
        ]

        # Skill map for easier lookup
        skill_map = {s.name: s for s in skills}

        print(f"Seeding {len(examples)} startups...")
        for ex in examples:
            creator = random.choice(users)
            
            # Check if already exists to avoid dupes
            existing = db.query(models.Startup).filter(models.Startup.title == ex["title"]).first()
            if existing:
                print(f"Skipping {ex['title']} - already exists")
                continue

            startup = models.Startup(
                title=ex["title"],
                problem_statement=ex["problem"],
                vision=ex["vision"],
                creator_id=creator.id,
                status="pitching"
            )
            
            # Associate skills
            found_skills = []
            for s_name in ex["required_skills"]:
                if s_name in skill_map:
                    found_skills.append(skill_map[s_name])
            
            startup.required_skills = found_skills
            
            # Add some random members (1-2)
            potential_members = [u for u in users if u.id != creator.id]
            if potential_members:
                members_count = random.randint(0, min(2, len(potential_members)))
                startup.members = random.sample(potential_members, members_count)

            db.add(startup)
            print(f"Added {ex['title']} (Creator: {creator.username})")

        db.commit()
        print("Done Seeding.")

    except Exception as e:
        print(f"Error: {e}")
        db.rollback()
    finally:
        db.close()

if __name__ == "__main__":
    seed_data()
